@host= http://localhost:3000
@access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjRhYWE0ZDIwMDFjYWVmNWEzYmU1YjQ5IiwidG9rZW5fdHlwZSI6MCwiaWF0IjoxNjg5NTEwMjY2LCJleHAiOjE2ODk1MTExNjZ9.1W-F3xpR9ScMgjQa5oXjtN3qU93J73Ivz0D7pZcbxSQ
@refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjRhYWE0ZDIwMDFjYWVmNWEzYmU1YjQ5IiwidG9rZW5fdHlwZSI6MSwiaWF0IjoxNjg5NTEwMjY2LCJleHAiOjE2OTgxNTAyNjZ9.aDsv_S6QqXmqBcTZ3Co0vjdu99SJld0lU0Vw4pVJoNU

###
GET {{host}} HTTP/1.1


### 

GET {{host}}/user/twitters HTTP/1.1

###

POST  {{host}}/users/login HTTP/1.1
content-type: application/json

{
    "email": "abc@gmail.com",
    "password": "Pacode"
}

### Register

POST  {{host}}/users/register HTTP/1.1
content-type: application/json

{
    "name" : "hoa",
    "email": "test10@gmail.com",
    "password": "Abc12345",
    "confirm_password": "Abc12345",
    "date_of_birth" : "2023-07-08T08:26:33.781Z"
}

### Login

POST  {{host}}/users/login HTTP/1.1
content-type: application/json

{

    "email": "test10@gmail.com",
    "password": "Abc12345"
   
}

### Logout

POST  {{host}}/users/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "refresh_token" : "{{refresh_token}}"
}


### Forgor password

POST  {{host}}/users/forgot-password HTTP/1.1
Content-Type: application/json

{
    "email" : "test10@gmail.com"
}

### Verify Forgor password token

POST  {{host}}/users/verify-forgot-password HTTP/1.1
Content-Type: application/json

{
    "forgot_password_token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjRhYWE0ZDIwMDFjYWVmNWEzYmU1YjQ5IiwidG9rZW5fdHlwZSI6MiwiaWF0IjoxNjg5NDI5MDc5LCJleHAiOjE2ODk1MTU0Nzl9.Nerww3LDP2iLJv3Tp1BjaR_IT4TTbPevqTR2N_izk1g"
}


### Reset password

POST  {{host}}/users/reset-password HTTP/1.1
Content-Type: application/json

{
    "forgot_password_token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjRhYWE0ZDIwMDFjYWVmNWEzYmU1YjQ5IiwidG9rZW5fdHlwZSI6MiwiaWF0IjoxNjg5NDMxNjQ5LCJleHAiOjE2ODk1MTgwNDl9.q2Uj81V5SZCPTCnjf28-k-Uv7dKIVGP3ex989XbcdEc"
    ,"password" : "Abc12345"
    ,"confirm_password" : "Abc12345"
}



### get user information

GET  {{host}}/users/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}
